/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KinksExplorerRouteImport } from './routes/kinks-explorer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KinksSlugRouteImport } from './routes/kinks.$slug'

const KinksExplorerRoute = KinksExplorerRouteImport.update({
  id: '/kinks-explorer',
  path: '/kinks-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KinksSlugRoute = KinksSlugRouteImport.update({
  id: '/kinks/$slug',
  path: '/kinks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kinks-explorer': typeof KinksExplorerRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kinks-explorer': typeof KinksExplorerRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kinks-explorer': typeof KinksExplorerRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kinks-explorer' | '/kinks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kinks-explorer' | '/kinks/$slug'
  id: '__root__' | '/' | '/kinks-explorer' | '/kinks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KinksExplorerRoute: typeof KinksExplorerRoute
  KinksSlugRoute: typeof KinksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kinks-explorer': {
      id: '/kinks-explorer'
      path: '/kinks-explorer'
      fullPath: '/kinks-explorer'
      preLoaderRoute: typeof KinksExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinks/$slug': {
      id: '/kinks/$slug'
      path: '/kinks/$slug'
      fullPath: '/kinks/$slug'
      preLoaderRoute: typeof KinksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KinksExplorerRoute: KinksExplorerRoute,
  KinksSlugRoute: KinksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
