/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KinksExplorerRouteImport } from './routes/kinks-explorer'
import { Route as HerDesiresRouteImport } from './routes/her-desires'
import { Route as FreebiesRouteImport } from './routes/freebies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KinksSlugRouteImport } from './routes/kinks.$slug'
import { Route as HerDesiresChapterRouteImport } from './routes/her-desires.$chapter'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const KinksExplorerRoute = KinksExplorerRouteImport.update({
  id: '/kinks-explorer',
  path: '/kinks-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const HerDesiresRoute = HerDesiresRouteImport.update({
  id: '/her-desires',
  path: '/her-desires',
  getParentRoute: () => rootRouteImport,
} as any)
const FreebiesRoute = FreebiesRouteImport.update({
  id: '/freebies',
  path: '/freebies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KinksSlugRoute = KinksSlugRouteImport.update({
  id: '/kinks/$slug',
  path: '/kinks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HerDesiresChapterRoute = HerDesiresChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => HerDesiresRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/freebies': typeof FreebiesRoute
  '/her-desires': typeof HerDesiresRouteWithChildren
  '/kinks-explorer': typeof KinksExplorerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/her-desires/$chapter': typeof HerDesiresChapterRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/freebies': typeof FreebiesRoute
  '/her-desires': typeof HerDesiresRouteWithChildren
  '/kinks-explorer': typeof KinksExplorerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/her-desires/$chapter': typeof HerDesiresChapterRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/freebies': typeof FreebiesRoute
  '/her-desires': typeof HerDesiresRouteWithChildren
  '/kinks-explorer': typeof KinksExplorerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/her-desires/$chapter': typeof HerDesiresChapterRoute
  '/kinks/$slug': typeof KinksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/freebies'
    | '/her-desires'
    | '/kinks-explorer'
    | '/blog/$slug'
    | '/her-desires/$chapter'
    | '/kinks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/freebies'
    | '/her-desires'
    | '/kinks-explorer'
    | '/blog/$slug'
    | '/her-desires/$chapter'
    | '/kinks/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/freebies'
    | '/her-desires'
    | '/kinks-explorer'
    | '/blog/$slug'
    | '/her-desires/$chapter'
    | '/kinks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  FreebiesRoute: typeof FreebiesRoute
  HerDesiresRoute: typeof HerDesiresRouteWithChildren
  KinksExplorerRoute: typeof KinksExplorerRoute
  KinksSlugRoute: typeof KinksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kinks-explorer': {
      id: '/kinks-explorer'
      path: '/kinks-explorer'
      fullPath: '/kinks-explorer'
      preLoaderRoute: typeof KinksExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/her-desires': {
      id: '/her-desires'
      path: '/her-desires'
      fullPath: '/her-desires'
      preLoaderRoute: typeof HerDesiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freebies': {
      id: '/freebies'
      path: '/freebies'
      fullPath: '/freebies'
      preLoaderRoute: typeof FreebiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinks/$slug': {
      id: '/kinks/$slug'
      path: '/kinks/$slug'
      fullPath: '/kinks/$slug'
      preLoaderRoute: typeof KinksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/her-desires/$chapter': {
      id: '/her-desires/$chapter'
      path: '/$chapter'
      fullPath: '/her-desires/$chapter'
      preLoaderRoute: typeof HerDesiresChapterRouteImport
      parentRoute: typeof HerDesiresRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HerDesiresRouteChildren {
  HerDesiresChapterRoute: typeof HerDesiresChapterRoute
}

const HerDesiresRouteChildren: HerDesiresRouteChildren = {
  HerDesiresChapterRoute: HerDesiresChapterRoute,
}

const HerDesiresRouteWithChildren = HerDesiresRoute._addFileChildren(
  HerDesiresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  FreebiesRoute: FreebiesRoute,
  HerDesiresRoute: HerDesiresRouteWithChildren,
  KinksExplorerRoute: KinksExplorerRoute,
  KinksSlugRoute: KinksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
